workflows:
  android-workflow:
    name: Android Build Fix
    instance_type: mac_mini_m2
    max_build_duration: 20
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean Old Android
        script: |
          flutter clean
          rm -rf android
          flutter create . --platforms=android --org com.sklmtrip.velipoodhaam --project-name velipoodhaam
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons -v
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
