workflows:
  android-workflow:
    name: Velipoodhaam Build
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create and Patch Android
        script: |
          flutter create . --platforms=android --org com.velipoodhaam.vayvi
          sed -i '' 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/' android/app/build.gradle || sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/' android/app/build.gradle
          sed -i '' 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion 34/' android/app/build.gradle || sed -i 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion 34/' android/app/build.gradle
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build split APKs
        script: |
          flutter build apk --release --split-per-abi --obfuscate --split-debug-info=./symbols --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
