name: velipoodhaam
description: TRIP KI VELTHAAM by Sai Ram Charan SKLM - Travel App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  http: ^1.2.0

flutter:
  uses-material-design: true
