description: Trip Ki Velthaam - Travel App by Sai Ram Charan
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  share_plus: ^8.0.2
  google_generative_ai: ^0.4.4
flutter:
  uses-material-design: true
